name: Build

on:
  push:
    paths:
      - 'common/**'
      - 'config/**'
      - 'network/**'
      - 'server/**'
      - 'go.mod'
      - 'go.sum'
      - 'main.go'
      - '.github/workflows/go.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build Linux-amd64
      run: env GOOS=linux GOARCH=amd64 go build -v
        
    - name: Upload Linux-amd64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux-amd64
        path: |
          ./erupe-ce
          ./config.json
          ./www/
          ./savedata/
          ./bin/
          ./bundled-schema/

    - name: Build Windows-amd64
      run: env GOOS=windows GOARCH=amd64 go build -v
      
    - name: Upload Windows-amd64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows-amd64
        path: |
          ./erupe-ce.exe
          ./config.json
          ./www/
          ./savedata/
          ./bin/
          ./bundled-schema/
